name: fitpay_dart_sdk
description: FitPay Dart SDK
version: 0.0.1
homepage: https://github.com/fitpay/fitpay-dart-sdk
author: FitPay <sdk@fit-pay.com>

environment:
    sdk: '>=2.2.0 <3.0.0'

dependencies:
    json_annotation:
    corsac_jwt:
    http:

dev_dependencies:
    pedantic:
    test:
    build_runner:
    build_test:
    json_serializable:
